// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgygauingklrxxpxcfua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJneWdhdWluZ2tscnh4cHhjZnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDAxNjksImV4cCI6MjA2MDgxNjE2OX0.TmcbIIEF_D6GzGHI5-kDS8c-WgWFH-bZZ95DcfENuX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);